# -*- coding: utf-8 -*-
"""test_2U-Net

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_1-iGCycw8ISnstOW2vzcSRk86nch-e
"""

from google.colab import drive
drive.mount('/content/drive')

!cp -r /content/drive/MyDrive/img/musk /content/musk/

import os
import time
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as T
from PIL import Image
import matplotlib.pyplot as plt
from skimage.metrics import peak_signal_noise_ratio as psnr_metric
from skimage.metrics import structural_similarity as ssim_metric

# фіксація seed для стабільності експериментів
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Використовується пристрій: {device}")

class FaceBlurDataset(Dataset):
    def __init__(self, folder_path, patch_size=256):
        self.folder_path = folder_path
        self.patch_size = patch_size

        # Зчитуємо всі файли з папки зобажень
        self.image_filenames = [f for f in sorted(os.listdir(folder_path)) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

        # Налаштування розмиття Гаусса
        self.blur_transform = T.GaussianBlur(kernel_size=15, sigma=4.0)
        self.to_tensor = T.ToTensor()

    def __len__(self):
        return len(self.image_filenames)

    def __getitem__(self, idx):
        filename = self.image_filenames[idx]
        img_path = os.path.join(self.folder_path, filename)

        # Завантажуємо оригінальне зобр
        sharp_img = Image.open(img_path).convert('RGB')
        w, h = sharp_img.size

        # Якщо картинка замала хоча б по одній стороні, збільшуємо її, щоб менша сторона була мінімум 256
        if h < self.patch_size or w < self.patch_size:
            if h < w:
                new_h = self.patch_size
                new_w = int(w * (self.patch_size / h))
            else:
                new_w = self.patch_size
                new_h = int(h * (self.patch_size / w))
            sharp_img = sharp_img.resize((new_w, new_h), resample=Image.BICUBIC)

        # Тепер 256x256 гарантовано пройде без помилок
        sharp_patch = T.RandomCrop(self.patch_size)(sharp_img)
        sharp_tensor = self.to_tensor(sharp_patch)

        # Створюємо розмитий вхід для нейромережі
        blur_tensor = self.blur_transform(sharp_tensor)

        return blur_tensor, sharp_tensor

# Шлях до папки
FACE_DATA_DIR = '/content/musk'

# Ініціалізуємо повний датасет
full_dataset = FaceBlurDataset(FACE_DATA_DIR, patch_size=256)


# Ділимо вибірку: 90% на навчання, 10% на валідацію/тест
train_size = int(0.9 * len(full_dataset))
val_size = len(full_dataset) - train_size

train_dataset, val_dataset = torch.utils.data.random_split(full_dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, drop_last=True)
val_loader = DataLoader(val_dataset, batch_size=4, shuffle=False)

print(f"Успішно завантажено обличчя!")
print(f"Картинок для навчання (патчів): {len(train_dataset)}, для валідації: {len(val_dataset)}")

class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )
    def forward(self, x):
        return self.conv(x)

class UNetResizeConv(nn.Module):
    def __init__(self, in_channels=3, out_channels=3):
        super().__init__()
        # Енкодер
        self.inc = DoubleConv(in_channels, 64)
        self.down1 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(64, 128))
        self.down2 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(128, 256))
        self.down3 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(256, 512))

        # Декодер (Resize-Convolution)
        self.up1 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.conv_up1 = DoubleConv(512 + 256, 256)

        self.up2 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.conv_up2 = DoubleConv(256 + 128, 128)

        self.up3 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.conv_up3 = DoubleConv(128 + 64, 64)

        self.outc = nn.Sequential(
            nn.Conv2d(64, out_channels, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x1 = self.inc(x)
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        x4 = self.down3(x3)

        x = self.up1(x4)
        x = torch.cat([x, x3], dim=1)
        x = self.conv_up1(x)

        x = self.up2(x)
        x = torch.cat([x, x2], dim=1)
        x = self.conv_up2(x)

        x = self.up3(x)
        x = torch.cat([x, x1], dim=1)
        x = self.conv_up3(x)

        return self.outc(x)

# Ініціалізація
model = UNetResizeConv().to(device)
criterion = nn.L1Loss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

import time
import pandas as pd  # Додаємо бібліотеку для роботи з таблицями
import os

#  НАЛАШТУВАННЯ ЗБЕРЕЖЕННЯ НА ГУГЛ ДИСК
# Шлях до папки на  Диску
drive_folder = '/content/drive/MyDrive/Diploma_Results/'
os.makedirs(drive_folder, exist_ok=True)  # Автоматично створить папку, якщо її немає
csv_save_path = os.path.join(drive_folder, 'training_history_musk.csv')

epochs = 75

# ЗБИРАЮТЬ ДАНІ АВТOМАТИЧНO
train_losses_history = []
val_losses_history = []
epoch_times_history = []  #  масив для збереження часу кожної епохи

print("=== СТАРТ НАВЧАННЯ НА ДАТАСЕТІ ОБЛИЧ (MUSK) ===")
print(f"{'Епоха':<8} | {'Train Loss':<12} | {'Val Loss':<12} | {'Час (сек)':<10}")
print("-" * 50)

for epoch in range(epochs):
    start_time = time.time()

    # Навчання
    model.train()
    train_loss = 0.0
    for blur_batch, sharp_batch in train_loader:
        blur_batch = blur_batch.to(device)
        sharp_batch = sharp_batch.to(device)

        optimizer.zero_grad()
        outputs = model(blur_batch)
        loss = criterion(outputs, sharp_batch)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    # Валідація
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for blur_batch, sharp_batch in val_loader:
            blur_batch = blur_batch.to(device)
            sharp_batch = sharp_batch.to(device)
            outputs = model(blur_batch)
            loss = criterion(outputs, sharp_batch)
            val_loss += loss.item()

    epoch_time = time.time() - start_time
    avg_train = train_loss / len(train_loader)
    avg_val = val_loss / len(val_loader)

    #  АВТOМАТИЧНЕ ЗБЕРЕЖЕННЯ ЦИФР ПІСЛЯ ЕПOХИ
    train_losses_history.append(avg_train)
    val_losses_history.append(avg_val)
    epoch_times_history.append(epoch_time)

    print(f"{epoch+1:<8} | {avg_train:<12.4f} | {avg_val:<12.4f} | {epoch_time:<10.1f}")

print("\n Модель успішно навчена на базі облич користувача!")

# --- БЛOК АВТOМАТИЧНOГO ЕКСПOРТУ В ТАБЛИЦЮ ---
print("\n Збереження результатів експерименту на Google Диск...")

# Створюємо структуровану таблицю (DataFrame)
df_history = pd.DataFrame({
    'Epoch': list(range(1, epochs + 1)),
    'Train_Loss_MAE': train_losses_history,
    'Val_Loss_MAE': val_losses_history,
    'Duration_Sec': epoch_times_history
})

# Зберігаємо у файл CSV без індексів рядків
df_history.to_csv(csv_save_path, index=False)

print(f" Таблицю успішно збережено за шляхом:\n{csv_save_path}")

import torch
import torchvision.transforms as T
import numpy as np
from PIL import Image
import os
import matplotlib.pyplot as plt
from skimage.metrics import peak_signal_noise_ratio as psnr_metric
from skimage.metrics import structural_similarity as ssim_metric

# 1. Переводимо модель в режим оцінки
model.eval()

# 2. Завантажуємо перше повнорозмірне фото
all_files = [f for f in sorted(os.listdir(FACE_DATA_DIR)) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
test_filename = all_files[7]
full_img_path = os.path.join(FACE_DATA_DIR, test_filename)

hr_pil = Image.open(full_img_path).convert('RGB')

# Примусово робимо розмір картинки кратнішим для безшовного змішування
W_target, H_target = 512, 512  # Стандартний квадрат, ідеальний для облич та U-Net
hr_pil = hr_pil.resize((W_target, H_target), resample=Image.BICUBIC)
W, H = hr_pil.size

# Штучно створюємо розмите фото для тесту
blur_transform = T.GaussianBlur(kernel_size=15, sigma=4.0)
to_tensor = T.ToTensor()

hr_tensor = to_tensor(hr_pil)
lr_tensor = blur_transform(hr_tensor)

# Конвертуємо в NumPy для метрик порівняння [0, 1]
hr_np = np.clip(hr_tensor.permute(1, 2, 0).numpy(), 0.0, 1.0)
lr_np = np.clip(lr_tensor.permute(1, 2, 0).numpy(), 0.0, 1.0)

# 3. БЕЗШОВНИЙ ТАЙЛИНГ (Працює бездоганно на квадраті 512x512)
patch_size = 256
stride = 128
output_canvas = torch.zeros_like(hr_tensor)
weight_canvas = torch.zeros(H, W)

mask_1d = torch.linspace(0, 1, steps=patch_size)
mask_1d = torch.min(mask_1d, 1 - mask_1d) * 2
mask_1d = torch.clamp(mask_1d, 0, 1)
mask_2d = mask_1d.view(1, -1) * mask_1d.view(-1, 1)

print(f"Обробка повного портрета: {test_filename} (Приведено до {W}x{H} для тесту)...")

with torch.no_grad():
    for y in range(0, H - patch_size + 1, stride):
        for x in range(0, W - patch_size + 1, stride):
            patch_lr = lr_tensor[:, y:y+patch_size, x:x+patch_size].unsqueeze(0).to(device)
            patch_pred = model(patch_lr).squeeze(0).cpu()
            patch_pred = torch.clamp(patch_pred, 0, 1)

            output_canvas[:, y:y+patch_size, x:x+patch_size] += patch_pred * mask_2d
            weight_canvas[y:y+patch_size, x:x+patch_size] += mask_2d

weight_canvas[weight_canvas == 0] = 1.0
output_canvas /= weight_canvas
output_canvas = torch.clamp(output_canvas, 0, 1)

restored_np = np.clip(output_canvas.permute(1, 2, 0).numpy(), 0.0, 1.0)

# --- МАТЕМАТИЧНИЙ РОЗРАХУНОК ОНОВЛЕНИХ МЕТРИК ЕФЕКТИВНОСТІ ---
psnr_blur = psnr_metric(hr_np, lr_np, data_range=1.0)
ssim_blur = ssim_metric(hr_np, lr_np, data_range=1.0, channel_axis=2)

psnr_restored = psnr_metric(hr_np, restored_np, data_range=1.0)
ssim_restored = ssim_metric(hr_np, restored_np, data_range=1.0, channel_axis=2)

print("\n" + "="*45)
print(" ФІНАЛЬНЕ ДОСЛІДЖЕННЯ ЕФЕКТИВНОСТІ (БЕЗ ШУМУ):")
print(f"Вхідне розмиття -> PSNR: {psnr_blur:.2f} dB | SSIM: {ssim_blur:.4f}")
print(f"Після U-Net     -> PSNR: {psnr_restored:.2f} dB | SSIM: {ssim_restored:.4f}")
print("="*45)

# --- ВІДОБРАЖЕННЯ ТА ЗБЕРЕЖЕННЯ ---
fig = plt.figure(figsize=(20, 7), dpi=150)
plt.subplot(1, 3, 1)
plt.imshow(lr_np)
plt.title(f"Вхід (PSNR: {psnr_blur:.2f} dB)", fontsize=14)
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(restored_np)
plt.title(f"Вихід U-Net (PSNR: {psnr_restored:.2f} dB)", fontsize=14)
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(hr_np)
plt.title("Оригінал (Ground Truth)", fontsize=14)
plt.axis('off')

plt.tight_layout()
try:
    plt.savefig('/content/drive/MyDrive/diploma/face_deblur_fixed_panel.png', bbox_inches='tight', dpi=150)
    print("🎉 Панель успішно збережено на Google Диск!")
except:
    plt.savefig('face_deblur_fixed_panel.png', bbox_inches='tight', dpi=150)
plt.show()

# КОМІРКА №5а: Автоматична побудова графіка на основі збереженої історії
# Кількість епох визначається автоматично за довжиною масиву історії
epochs_range = list(range(1, len(train_losses_history) + 1))

plt.figure(figsize=(12, 6), dpi=150)
plt.plot(epochs_range, train_losses_history, label='Помилка навчання (Train Loss MAE)', color='#1f77b4', linewidth=2, marker='o', markersize=3, alpha=0.8)
plt.plot(epochs_range, val_losses_history, label='Помилка валідації (Val Loss MAE)', color='#ff7f0e', linewidth=2, marker='s', markersize=3, alpha=0.8)

plt.title('Криві збіжності моделі U-Net протягом навчання', fontsize=14, pad=15, fontweight='bold')
plt.xlabel('Епоха навчання', fontsize=12)
plt.ylabel('Значення функції втрат (L1 Loss)', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.5)
plt.legend(fontsize=11)

# Зберігаємо графік у папку diploma на Гугл Диску
try:
    plt.savefig('/content/drive/MyDrive/diploma/unet_face_loss_auto.png', bbox_inches='tight', dpi=200)
    print("🎉 Графік успішно збережено на Ваш Google Диск (unet_face_loss_auto.png)")
except:
    plt.savefig('unet_face_loss_auto.png', bbox_inches='tight', dpi=200)
    print("⚠️ Диск не підключено, графік збережено локально в Colab.")

plt.show()

# ДЕБАГ-КОМІРКА: Перевірка діапазонів та розмірів перед тайлингом
print("=== ТЕСТУВАННЯ ТИПІВ ДАНИХ ===")
print(f"hr_tensor - Мін: {hr_tensor.min().item():.4f}, Макс: {hr_tensor.max().item():.4f}, Формат: {hr_tensor.shape}")
print(f"lr_tensor - Мін: {lr_tensor.min().item():.4f}, Макс: {lr_tensor.max().item():.4f}, Формат: {lr_tensor.shape}")

# Перевіримо один тестовий патч через модель
test_patch = lr_tensor[:, 0:256, 0:256].unsqueeze(0).to(device)
with torch.no_grad():
    test_out = model(test_patch).cpu().squeeze(0)

print(f"Вихід моделі (Патч) - Мін: {test_out.min().item():.4f}, Макс: {test_out.max().item():.4f}, Формат: {test_out.shape}")
print(f"Канва виходу (output_canvas) - Мін: {output_canvas.min().item():.4f}, Макс: {output_canvas.max().item():.4f}")

"""
**Adaptive U-Net**"""

import torch
import torch.nn as nn
import torch.optim as optim

# 1. МЕХАНІЗМ АДАПТИВНОЇ УВАГИ (Squeeze-and-Excitation)
class AdaptiveSEBlock(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        self.squeeze = nn.AdaptiveAvgPool2d(1)
        self.excitation = nn.Sequential(
            nn.Linear(channels, channels // reduction, bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(channels // reduction, channels, bias=False),
            nn.Sigmoid()
        )

    def forward(self, x):
        b, c, _, _ = x.size()
        y = self.squeeze(x).view(b, c)
        y = self.excitation(y).view(b, c, 1, 1)
        return x * y.expand_as(x)

# 2. АДАПТИВНА ПОДВІЙНА ЗГОРТКА (Базовий будівельний блок)
class AdaptiveDoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )
        self.adaptive_se = AdaptiveSEBlock(out_channels)

    def forward(self, x):
        x = self.conv(x)
        x = self.adaptive_se(x) # Мережа сама вирішує, які канали важливіші
        return x

# 3. ГОЛОВНА АРХІТЕКТУРА: ADAPTIVE U-NET (з Resize-Convolution)
class AdaptiveUNet(nn.Module):
    def __init__(self, in_channels=3, out_channels=3):
        super().__init__()

        # ЕНКОДЕР (Шлях стиснення з адаптивними блоками)
        self.inc = AdaptiveDoubleConv(in_channels, 64)
        self.down1 = nn.Sequential(nn.MaxPool2d(2), AdaptiveDoubleConv(64, 128))
        self.down2 = nn.Sequential(nn.MaxPool2d(2), AdaptiveDoubleConv(128, 256))
        self.down3 = nn.Sequential(nn.MaxPool2d(2), AdaptiveDoubleConv(256, 512))

        # ДЕКОДЕР (Шлях розширення з Resize-Convolution)
        self.up1 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.conv_up1 = AdaptiveDoubleConv(512 + 256, 256)

        self.up2 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.conv_up2 = AdaptiveDoubleConv(256 + 128, 128)

        self.up3 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.conv_up3 = AdaptiveDoubleConv(128 + 64, 64)

        # фінальний вихід
        self.outc = nn.Sequential(
            nn.Conv2d(64, out_channels, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x1 = self.inc(x)
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        x4 = self.down3(x3)

        x = self.up1(x4)
        x = torch.cat([x, x3], dim=1)
        x = self.conv_up1(x)

        x = self.up2(x)
        x = torch.cat([x, x2], dim=1)
        x = self.conv_up2(x)

        x = self.up3(x)
        x = torch.cat([x, x1], dim=1)
        x = self.conv_up3(x)

        return self.outc(x)

# 4. ІНІЦІАЛІЗАЦІЯ НЕЗАЛЕЖНОЇ МОДЕЛІ (Використовуємо нові змінні)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Називаємо змінні з приставкою adaptive_, щоб не зачепити стару модель
adaptive_model = AdaptiveUNet().to(device)
adaptive_criterion = nn.L1Loss()
adaptive_optimizer = optim.Adam(adaptive_model.parameters(), lr=0.001)

print("🚀 Незалежна архітектура Adaptive U-Net успішно ініціалізована на пристрої:", device)
print("Стара модель (UNetResizeConv) залишається в пам'яті для порівняння.")

import time
import pandas as pd  # Додаємо бібліотеку для таблиць
import os

# --- НАЛАШТУВАННЯ ЗБЕРЕЖЕННЯ НА ГУГЛ ДИСК ---
drive_folder = '/content/drive/MyDrive/Diploma_Results/'
os.makedirs(drive_folder, exist_ok=True)  # Створить папку, якщо її немає
csv_adaptive_path = os.path.join(drive_folder, 'adaptive_training_history_5_epochs.csv')

adaptive_epochs = 75

adaptive_train_losses = []
adaptive_val_losses = []
adaptive_epoch_times = [] # Масив для збереження часу епох

print("=== СТАРТ НАВЧАННЯ ADAPTIVE U-NET ===")
print(f"{'Епоха':<8} | {'Train Loss':<12} | {'Val Loss':<12} | {'Час (сек)':<10}")
print("-" * 50)

for epoch in range(adaptive_epochs):
    start_time = time.time()

    # Навчання адаптивної моделі
    adaptive_model.train()
    train_loss = 0.0
    for blur_batch, sharp_batch in train_loader:
        blur_batch = blur_batch.to(device)
        sharp_batch = sharp_batch.to(device)

        adaptive_optimizer.zero_grad()
        outputs = adaptive_model(blur_batch)
        loss = adaptive_criterion(outputs, sharp_batch)
        loss.backward()
        adaptive_optimizer.step()

        train_loss += loss.item()

    # Валідація адаптивної моделі
    adaptive_model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for blur_batch, sharp_batch in val_loader:
            blur_batch = blur_batch.to(device)
            sharp_batch = sharp_batch.to(device)
            outputs = adaptive_model(blur_batch)
            loss = adaptive_criterion(outputs, sharp_batch)
            val_loss += loss.item()

    epoch_time = time.time() - start_time
    avg_train = train_loss / len(train_loader)
    avg_val = val_loss / len(val_loader)

    # Збереження цифр
    adaptive_train_losses.append(avg_train)
    adaptive_val_losses.append(avg_val)
    adaptive_epoch_times.append(epoch_time)

    print(f"{epoch+1:<8} | {avg_train:<12.4f} | {avg_val:<12.4f} | {epoch_time:<10.1f}")

print("\n Адаптивна модель успішно навчена!")

# --- БЛОК АВТОМАТИЧНОГО ЗБЕРЕЖЕННЯ ТАБЛИЦІ ---
print("\n💾 Збереження результатів тесту на Google Диск...")

df_adaptive_5 = pd.DataFrame({
    'Epoch': list(range(1, adaptive_epochs + 1)),
    'Adaptive_Train_Loss': adaptive_train_losses,
    'Adaptive_Val_Loss': adaptive_val_losses,
    'Duration_Sec': adaptive_epoch_times
})

df_adaptive_5.to_csv(csv_adaptive_path, index=False)
print(f" Таблицю адаптивної моделі (5 епох) успішно збережено за шляхом:\n{csv_adaptive_path}")

import torch
import torchvision.transforms as T
import numpy as np
from PIL import Image
import os
import matplotlib.pyplot as plt
from skimage.metrics import peak_signal_noise_ratio as psnr_metric
from skimage.metrics import structural_similarity as ssim_metric

# 1. Переводимо АДАПТИВНУ модель в режим оцінки
adaptive_model.eval()

# Завантажуємо ТЕ САМЕ фото для чесного А/В тестування
all_files = [f for f in sorted(os.listdir(FACE_DATA_DIR)) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
test_filename = all_files[7] # Індекс 7, як і в минулому тесті
full_img_path = os.path.join(FACE_DATA_DIR, test_filename)

hr_pil = Image.open(full_img_path).convert('RGB')
W_target, H_target = 512, 512
hr_pil = hr_pil.resize((W_target, H_target), resample=Image.BICUBIC)
W, H = hr_pil.size

# Створюємо розмите фото
blur_transform = T.GaussianBlur(kernel_size=15, sigma=4.0)
to_tensor = T.ToTensor()
hr_tensor = to_tensor(hr_pil)
lr_tensor = blur_transform(hr_tensor)

hr_np = np.clip(hr_tensor.permute(1, 2, 0).numpy(), 0.0, 1.0)
lr_np = np.clip(lr_tensor.permute(1, 2, 0).numpy(), 0.0, 1.0)

# 2. БЕЗШОВНИЙ ТАЙЛИНГ ДЛЯ АДАПТИВНОЇ МОДЕЛІ
patch_size = 256
stride = 128
adaptive_output = torch.zeros_like(hr_tensor)
weight_canvas = torch.zeros(H, W)

mask_1d = torch.linspace(0, 1, steps=patch_size)
mask_1d = torch.min(mask_1d, 1 - mask_1d) * 2
mask_1d = torch.clamp(mask_1d, 0, 1)
mask_2d = mask_1d.view(1, -1) * mask_1d.view(-1, 1)

print(f"Обробка повного портрета: {test_filename} через ADAPTIVE U-NET...")

with torch.no_grad():
    for y in range(0, H - patch_size + 1, stride):
        for x in range(0, W - patch_size + 1, stride):
            patch_lr = lr_tensor[:, y:y+patch_size, x:x+patch_size].unsqueeze(0).to(device)

            # ВАЖЛИВО: Використовуємо adaptive_model
            patch_pred = adaptive_model(patch_lr).squeeze(0).cpu()
            patch_pred = torch.clamp(patch_pred, 0, 1)

            adaptive_output[:, y:y+patch_size, x:x+patch_size] += patch_pred * mask_2d
            weight_canvas[y:y+patch_size, x:x+patch_size] += mask_2d

weight_canvas[weight_canvas == 0] = 1.0
adaptive_output /= weight_canvas
adaptive_output = torch.clamp(adaptive_output, 0, 1)

adaptive_restored_np = np.clip(adaptive_output.permute(1, 2, 0).numpy(), 0.0, 1.0)

# 3. МАТЕМАТИЧНИЙ РОЗРАХУНОК МЕТРИК
psnr_blur = psnr_metric(hr_np, lr_np, data_range=1.0)
ssim_blur = ssim_metric(hr_np, lr_np, data_range=1.0, channel_axis=2)

psnr_adaptive = psnr_metric(hr_np, adaptive_restored_np, data_range=1.0)
ssim_adaptive = ssim_metric(hr_np, adaptive_restored_np, data_range=1.0, channel_axis=2)

print("\n" + "="*45)
print(" ФІНАЛЬНІ РЕЗУЛЬТАТИ ADAPTIVE U-NET:")
print(f"Вхідне розмиття -> PSNR: {psnr_blur:.2f} dB | SSIM: {ssim_blur:.4f}")
print(f"Adaptive U-Net  -> PSNR: {psnr_adaptive:.2f} dB | SSIM: {ssim_adaptive:.4f}")
print("="*45)

# 4. ВІДОБРАЖЕННЯ ТА ЗБЕРЕЖЕННЯ
fig = plt.figure(figsize=(20, 7), dpi=150)
plt.subplot(1, 3, 1)
plt.imshow(lr_np)
plt.title(f"Вхід (PSNR: {psnr_blur:.2f} dB)", fontsize=14)
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(adaptive_restored_np)
plt.title(f"Вихід Adaptive U-Net (PSNR: {psnr_adaptive:.2f} dB)", fontsize=14)
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(hr_np)
plt.title("Оригінал (Ground Truth)", fontsize=14)
plt.axis('off')

plt.tight_layout()
try:
    plt.savefig('/content/drive/MyDrive/diploma/adaptive_deblur_panel.png', bbox_inches='tight', dpi=150)
    print(" Панель адаптивної моделі успішно збережено на Google Диск!")
except:
    plt.savefig('adaptive_deblur_panel.png', bbox_inches='tight', dpi=150)
plt.show()

import matplotlib.pyplot as plt

# Налаштування розміру та якості графіка
plt.figure(figsize=(10, 6), dpi=150)

# Малюємо лінії навчання та валідації для адаптивної моделі
plt.plot(adaptive_train_losses, label='Навчання (Train Loss)', color='teal', linewidth=2)
plt.plot(adaptive_val_losses, label='Валідація (Val Loss)', color='orange', linewidth=2)

# Оформлення графіка під стандарти диплома
plt.title('Динаміка навчання нейромережі Adaptive U-Net', fontsize=14, pad=15)
plt.xlabel('Епохи навчання', fontsize=12)
plt.ylabel('Функція втрат (L1 Loss)', fontsize=12)
plt.legend(fontsize=12, loc='upper right')
plt.grid(True, linestyle=':', alpha=0.7)
plt.tight_layout()

# Автоматичне збереження графіка для звіту
try:
    plt.savefig('/content/drive/MyDrive/diploma/adaptive_loss_plot.png', bbox_inches='tight', dpi=150)
    print("🎉 Графік адаптивної моделі успішно збережено на Google Диск!")
except:
    plt.savefig('adaptive_loss_plot.png', bbox_inches='tight', dpi=150)

# Виведення графіка
plt.show()

"""**графік порівняння**"""

import matplotlib.pyplot as plt
import numpy as np

# Збираємо наші метрики в масиви (змінні збереглися з попередніх комірок)
labels = ['Вхідне розмиття', 'Базова U-Net', 'Adaptive U-Net']

# Значення PSNR
psnr_values = [psnr_blur, psnr_restored, psnr_adaptive]

# Значення SSIM
ssim_values = [ssim_blur, ssim_restored, ssim_adaptive]

# Налаштовуємо полотно (два графіки поруч)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6), dpi=150)

x = np.arange(len(labels))
width = 0.5  # ширина стовпчиків

# --- 1. Графік для PSNR ---
bars1 = ax1.bar(x, psnr_values, width, color=['#95a5a6', '#3498db', '#e74c3c'], edgecolor='black', alpha=0.8)
ax1.set_ylabel('Значення PSNR (dB)', fontsize=12)
ax1.set_title('Порівняння метрики PSNR (Пікове відношення сигналу до шуму)', fontsize=12, pad=15)
ax1.set_xticks(x)
ax1.set_xticklabels(labels, fontsize=11)
ax1.grid(axis='y', linestyle='--', alpha=0.6)

# Додаємо цифри над стовпчиками
for bar in bars1:
    yval = bar.get_height()
    ax1.text(bar.get_x() + bar.get_width()/2, yval + 0.3, f'{yval:.2f}', ha='center', va='bottom', fontsize=11, fontweight='bold')

# --- 2. Графік для SSIM ---
bars2 = ax2.bar(x, ssim_values, width, color=['#95a5a6', '#2ecc71', '#9b59b6'], edgecolor='black', alpha=0.8)
ax2.set_ylabel('Значення SSIM', fontsize=12)
ax2.set_title('Порівняння метрики SSIM (Індекс структурної подібності)', fontsize=12, pad=15)
ax2.set_xticks(x)
ax2.set_xticklabels(labels, fontsize=11)
# Робимо ліміт для SSIM трохи вищим, щоб влізли написи
ax2.set_ylim(0.85, max(ssim_values) + 0.02)
ax2.grid(axis='y', linestyle='--', alpha=0.6)

# Додаємо цифри над стовпчиками
for bar in bars2:
    yval = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2, yval + 0.001, f'{yval:.4f}', ha='center', va='bottom', fontsize=11, fontweight='bold')

# Фінальне оформлення
plt.tight_layout()

# Збереження для диплома
try:
    plt.savefig('/content/drive/MyDrive/diploma/metrics_comparison_bar.png', bbox_inches='tight', dpi=150)
    print("🎉 Порівняльні гістограми успішно збережено на Google Диск!")
except:
    plt.savefig('metrics_comparison_bar.png', bbox_inches='tight', dpi=150)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Розраховуємо абсолютну різницю (похибку) між оригіналом і результатами мереж
# Беремо середнє по колірних каналах (RGB), щоб отримати двовимірну карту
error_base = np.mean(np.abs(hr_np - restored_np), axis=2)
error_adaptive = np.mean(np.abs(hr_np - adaptive_restored_np), axis=2)

# Налаштовуємо полотно
fig, axes = plt.subplots(1, 2, figsize=(14, 6), dpi=150)

# 1. Теплова карта для базової моделі
# Використовуємо палітру 'magma' або 'inferno', де чорний - нуль похибки, а яскравий - велика похибка
im1 = axes[0].imshow(error_base, cmap='inferno', vmin=0, vmax=0.15)
axes[0].set_title('Карта похибок: Базова U-Net', fontsize=14, pad=10)
axes[0].axis('off')
fig.colorbar(im1, ax=axes[0], fraction=0.046, pad=0.04, label='Абсолютна різниця пікселів')

# 2. Теплова карта для адаптивної моделі
im2 = axes[1].imshow(error_adaptive, cmap='inferno', vmin=0, vmax=0.15)
axes[1].set_title('Карта похибок: Adaptive U-Net', fontsize=14, pad=10)
axes[1].axis('off')
fig.colorbar(im2, ax=axes[1], fraction=0.046, pad=0.04, label='Абсолютна різниця пікселів')

plt.suptitle('Візуалізація просторового розподілу похибок (Error Heatmaps)', fontsize=16, y=1.02)
plt.tight_layout()

# Збереження графіка для диплома
try:
    plt.savefig('/content/drive/MyDrive/diploma/error_heatmaps.png', bbox_inches='tight', dpi=150)
    print(" Теплові карти успішно збережено на Google Диск!")
except:
    plt.savefig('error_heatmaps.png', bbox_inches='tight', dpi=150)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Вибираємо горизонтальну лінію для аналізу (середина зображення)
y_line = 256

# Беремо середнє значення яскравості по RGB-каналах (переводимо в градації сірого)
gray_gt = np.mean(hr_np, axis=2)
gray_blur = np.mean(lr_np, axis=2)
gray_base = np.mean(restored_np, axis=2)
gray_adaptive = np.mean(adaptive_restored_np, axis=2)

# Вирізаємо конкретний фрагмент по осі X (наприклад, з 150 до 350 пікселя),
# щоб наблизити (зум) конкретні деталі та переходи
x_start, x_end = 150, 350
slice_gt = gray_gt[y_line, x_start:x_end]
slice_blur = gray_blur[y_line, x_start:x_end]
slice_base = gray_base[y_line, x_start:x_end]
slice_adaptive = gray_adaptive[y_line, x_start:x_end]

# Побудова графіка
plt.figure(figsize=(12, 6), dpi=150)

# Малюємо лінії
plt.plot(slice_blur, label='Вхідне розмиття', color='gray', linestyle=':', linewidth=2)
plt.plot(slice_base, label='Базова U-Net', color='#3498db', alpha=0.8, linewidth=2)
plt.plot(slice_adaptive, label='Adaptive U-Net (SE)', color='#e74c3c', linewidth=2.5)
plt.plot(slice_gt, label='Оригінал (Ground Truth)', color='black', linestyle='--', linewidth=1.5)

# Оформлення
plt.title('Профіль інтенсивності пікселів (1D-зріз по горизонталі)', fontsize=14, pad=15)
plt.xlabel('Позиція пікселя по осі X (фрагмент)', fontsize=12)
plt.ylabel('Інтенсивність (Яскравість 0.0 - 1.0)', fontsize=12)
plt.legend(fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()

# Збереження
try:
    plt.savefig('/content/drive/MyDrive/diploma/1d_intensity_profile.png', bbox_inches='tight', dpi=150)
    print(" Профіль інтенсивності успішно збережено на Google Диск!")
except:
    plt.savefig('1d_intensity_profile.png', bbox_inches='tight', dpi=150)

plt.show()

import os
import torch
import numpy as np
import pandas as pd
from PIL import Image
import torchvision.transforms as T
import matplotlib.pyplot as plt
from skimage.metrics import peak_signal_noise_ratio as psnr_metric
from skimage.metrics import structural_similarity as ssim_metric

# 1. Переводимо обидві моделі в режим валідації
model.eval()
adaptive_model.eval()

# 2. Завантажуємо те саме тестове фото (Індекс 7, як у твоїх основних тестах)
all_files = [f for f in sorted(os.listdir(FACE_DATA_DIR)) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
test_filename = all_files[7]
full_img_path = os.path.join(FACE_DATA_DIR, test_filename)

hr_pil = Image.open(full_img_path).convert('RGB')
W_target, H_target = 512, 512  # Наш фіксований квадрат для чесного А/В тесту
hr_pil = hr_pil.resize((W_target, H_target), resample=Image.BICUBIC)
W, H = hr_pil.size

to_tensor = T.ToTensor()
hr_tensor = to_tensor(hr_pil)
hr_np = np.clip(hr_tensor.permute(1, 2, 0).numpy(), 0.0, 1.0)

# 3. Визначаємо 3 рівні деградації (Блюру) через параметри ядра Гаусса
blur_scenarios = {
    "Слабке розмиття (5x5)":  {"kernel": 5,  "sigma": 1.5},
    "Середнє розмиття (9x9)": {"kernel": 9,  "sigma": 4.0}, # Твій базовий варіант
    "Сильне розмиття (15x15)": {"kernel": 15, "sigma": 7.0}  # Стрес-тест
}

# Масиви для збереження результатів
stress_test_data = []
visual_panels = {} # Словник для збереження картинок для колажу

print("=== СТАРТ СТРЕС-ТЕСТУ: ОЦІНКА СТІЙКОСТІ ДО РІВНІВ БЛЮРУ ===")

# 4. Головний цикл експерименту
for level_name, params in blur_scenarios.items():
    print(f"\nТестування рівня: {level_name}...")

    # Динамічно створюємо трансформацію розмиття під поточний сценарій
    current_blur_transform = T.GaussianBlur(kernel_size=params["kernel"], sigma=params["sigma"])
    lr_tensor = current_blur_transform(hr_tensor)
    lr_np = np.clip(lr_tensor.permute(1, 2, 0).numpy(), 0.0, 1.0)

    # --- НАЛАШТУВАННЯ ТАЙЛИНГУ ДЛЯ ОБРОБКИ ПОВНОГО КАДРУ ---
    patch_size = 256
    stride = 128

    # Канва для базової U-Net
    output_base = torch.zeros_like(hr_tensor)
    # Канва для Adaptive U-Net
    output_adaptive = torch.zeros_like(hr_tensor)

    weight_canvas = torch.zeros(H, W)

    # Створення маски для згладжування швів (вікно)
    mask_1d = torch.linspace(0, 1, steps=patch_size)
    mask_1d = torch.min(mask_1d, 1 - mask_1d) * 2
    mask_1d = torch.clamp(mask_1d, 0, 1)
    mask_2d = mask_1d.view(1, -1) * mask_1d.view(-1, 1)

    # Прохід вікном по всьому зображенню
    with torch.no_grad():
        for y in range(0, H - patch_size + 1, stride):
            for x in range(0, W - patch_size + 1, stride):
                patch_lr = lr_tensor[:, y:y+patch_size, x:x+patch_size].unsqueeze(0).to(device)

                # Обробка базовою моделлю
                pred_base = model(patch_lr).squeeze(0).cpu()
                output_base[:, y:y+patch_size, x:x+patch_size] += torch.clamp(pred_base, 0, 1) * mask_2d

                # Обробка адаптивною моделлю
                pred_adaptive = adaptive_model(patch_lr).squeeze(0).cpu()
                output_adaptive[:, y:y+patch_size, x:x+patch_size] += torch.clamp(pred_adaptive, 0, 1) * mask_2d

                weight_canvas[y:y+patch_size, x:x+patch_size] += mask_2d

    # Нормалізація карт після тайлингу
    weight_canvas[weight_canvas == 0] = 1.0
    output_base /= weight_canvas
    output_adaptive /= weight_canvas

    restored_base_np = np.clip(output_base.permute(1, 2, 0).numpy(), 0.0, 1.0)
    restored_adaptive_np = np.clip(output_adaptive.permute(1, 2, 0).numpy(), 0.0, 1.0)

    # Зберігаємо масиви зображень для фінального рендеру колажу
    visual_panels[level_name] = {
        "lr": lr_np,
        "base": restored_base_np,
        "adaptive": restored_adaptive_np
    }

    # --- РОЗРАХУНОК МЕТРИК ДЛЯ ПОТОЧНОГО РІВНЯ ---
    psnr_lr = psnr_metric(hr_np, lr_np, data_range=1.0)
    ssim_lr = ssim_metric(hr_np, lr_np, data_range=1.0, channel_axis=2)

    psnr_b = psnr_metric(hr_np, restored_base_np, data_range=1.0)
    ssim_b = ssim_metric(hr_np, restored_base_np, data_range=1.0, channel_axis=2)

    psnr_a = psnr_metric(hr_np, restored_adaptive_np, data_range=1.0)
    ssim_a = ssim_metric(hr_np, restored_adaptive_np, data_range=1.0, channel_axis=2)

    # Записуємо дані у загальний звіт
    stress_test_data.append({
        "Рівень розмиття": level_name,
        "Вхід PSNR (dB)": round(psnr_lr, 2),
        "Вхід SSIM": round(ssim_lr, 4),
        "U-Net PSNR (dB)": round(psnr_b, 2),
        "U-Net SSIM": round(ssim_b, 4),
        "Adaptive U-Net PSNR (dB)": round(psnr_a, 2),
        "Adaptive U-Net SSIM": round(ssim_a, 4)
    })

print("\n🎉 Експеримент завершено! Формування фінальної таблиці результатів...")

# 5. Створення структурованого DataFrame та виведення в консоль
df_stress_results = pd.DataFrame(stress_test_data)
display(df_stress_results)

# Автоматичне збереження результатів у CSV на Google Диск
try:
    save_csv_path = '/content/drive/MyDrive/Diploma_Results/blur_robustness_results.csv'
    df_stress_results.to_csv(save_csv_path, index=False)
    print(f"✅ Результати успішно експортовано в CSV за шляхом: {save_csv_path}")
except:
    df_stress_results.to_csv('blur_robustness_results.csv', index=False)

# 6. ВІЗУАЛІЗАЦІЯ: Матриця результатів 3х3 для тексту диплома
fig, axes = plt.subplots(3, 3, figsize=(15, 15), dpi=150)
rows = list(blur_scenarios.keys())

for idx, row_name in enumerate(rows):
    data = visual_panels[row_name]
    metrics = stress_test_data[idx]

    # Перша колонка: Вхідне розмите фото
    axes[idx, 0].imshow(data["lr"])
    axes[idx, 0].set_title(f"Вхід: {row_name}\nPSNR: {metrics['Вхід PSNR (dB)']} dB | SSIM: {metrics['Вхід SSIM']}", fontsize=10)
    axes[idx, 0].axis('off')

    # Друга колонка: Результат Базової U-Net
    axes[idx, 1].imshow(data["base"])
    axes[idx, 1].set_title(f"Вихід Базова U-Net\nPSNR: {metrics['U-Net PSNR (dB)']} dB | SSIM: {metrics['U-Net SSIM']}", fontsize=10)
    axes[idx, 1].axis('off')

    # Третя колонка: Результат Adaptive U-Net
    axes[idx, 2].imshow(data["adaptive"])
    axes[idx, 2].set_title(f"Вихід Adaptive U-Net\nPSNR: {metrics['Adaptive U-Net PSNR (dB)']} dB | SSIM: {metrics['Adaptive U-Net SSIM']}", fontsize=10)
    axes[idx, 2].axis('off')

plt.tight_layout()
# Збереження великого колажу на диск
try:
    plt.savefig('/content/drive/MyDrive/diploma/blur_robustness_matrix.png', bbox_inches='tight', dpi=150)
    print(" Матрицю візуального порівняння 3х3 збережено на Google Диск!")
except:
    plt.savefig('blur_robustness_matrix.png', bbox_inches='tight', dpi=150)
plt.show()